openapi: 3.1.0
info:
  version: 1.0.0
  title: Products App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    The app with a list of Products and it's description
tags:
  - name: Products
    description: Operations with the list of Products
servers:
  - url: http://localhost:3000
  # - url: #посилання на задеплоєний сайт
paths:
  /products:
    get:
      $ref: ../swagger/paths/get.yaml
    post:
      $ref: ../swagger/paths/post.yaml
  /products/{id}:
    get:
      $ref: ../swagger/paths/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/{id}/patch.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
